version: '3.2'

services:
  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - 5672:5672
      - 15672:15672
    # https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

  poller:
    build:
      context: .
      dockerfile: poller.dockerfile
    environment:
      QUEUE_NAME: ${QUEUE_NAME}
      GITHUB_AUTH: ${GITHUB_AUTH}
      POLLER_NODES: ${POLLER_NODES}
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  jobs:
    build:
      context: .
      dockerfile: jobs.dockerfile
    environment:
      QUEUE_NAME: ${QUEUE_NAME}
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
